package org.example.cargo.dto;

import org.example.cargo.domain.user.User;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.springframework.context.annotation.Configuration;



@Mapper(componentModel = "spring")
public interface UserMapper {
//    @Mapping(target = "id", ignore = true) // ID is generated by the database
//    @Mapping(target = "createdAt", ignore = true) // Timestamps handled by persistence or service
//    @Mapping(target = "updatedAt", ignore = true)
//    User toEntity(UserCreateDto createDto);
//    //todo check wether needed or not
//  //  @Mapping(target = "password", ignore = true) // Never expose the raw password
//    UserResponseDto toDto(User user);
//    @Mapping(target = "id", ignore = true) // ID is used for lookup, not updated from DTO
//    @Mapping(target = "createdAt", ignore = true) // Typically don't update creation timestamp
//    @Mapping(target = "updatedAt", ignore = true)
//    void updateEntityFromDto(UserUpdateDto updateDto,@MappingTarget User user);
}
